version: "3.8"

services:
  broker:
    image: igorvicente0712/sbbs_broker:part03
    networks:
      - bbs_net

  pubsub_proxy:
    image: igorvicente0712/sbbs_pubsub_proxy:part03
    networks:
      - bbs_net

  reference:
    image: igorvicente0712/sbbs_reference:part03
    networks:
      - bbs_net

  server1:
    image: igorvicente0712/sbbs_server:part03
    environment:
      - SERVER_ID=server1
      - DB_PATH=/data/server1.db
      - BROKER_ADDR=tcp://broker:5556
      - PUBSUB_ADDR=tcp://pubsub_proxy:5557
      - REFERENCE_ADDR=tcp://reference:5560
    volumes:
      - ./data:/data
    depends_on:
      - broker
      - pubsub_proxy
      - reference
    networks:
      - bbs_net

  server2:
    image: igorvicente0712/sbbs_server:part03
    environment:
      - SERVER_ID=server2
      - DB_PATH=/data/server2.db
      - BROKER_ADDR=tcp://broker:5556
      - PUBSUB_ADDR=tcp://pubsub_proxy:5557
      - REFERENCE_ADDR=tcp://reference:5560
    volumes:
      - ./data:/data
    depends_on:
      - broker
      - pubsub_proxy
      - reference
    networks:
      - bbs_net

  bot1:
    image: igorvicente0712/sbbs_client:part03
    environment:
      - BOT_NAME=bot1
      - BROKER_ADDR=tcp://broker:5555
      - PUBSUB_ADDR=tcp://pubsub_proxy:5558
    depends_on:
      - broker
      - pubsub_proxy
      - server1
      - server2
    networks:
      - bbs_net

  bot2:
    image: igorvicente0712/sbbs_client:part03
    environment:
      - BOT_NAME=bot2
      - BROKER_ADDR=tcp://broker:5555
      - PUBSUB_ADDR=tcp://pubsub_proxy:5558
    depends_on:
      - broker
      - pubsub_proxy
      - server1
      - server2
    networks:
      - bbs_net

  bot3:
    image: igorvicente0712/sbbs_client:part03
    environment:
      - BOT_NAME=bot3
      - BROKER_ADDR=tcp://broker:5555
      - PUBSUB_ADDR=tcp://pubsub_proxy:5558
    depends_on:
      - broker
      - pubsub_proxy
      - server1
      - server2
    networks:
      - bbs_net

networks:
  bbs_net:
    driver: bridge